{{ if eq .Values.fibo.ingress.enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fibo-ingress
  annotations:
    {{- range $key, $value := .Values.fibo.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.fibo.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fibo-service
                port:
                  number: 80
{{ end }}